apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: tuwnguyendocker/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: tuwnguyendocker/tk-client
      context: client
      sync:
        manual:
          - src: '**/*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: tuwnguyendocker/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: tuwnguyendocker/orders
      context: orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: tuwnguyendocker/expiration
      context: expiration
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: tuwnguyendocker/payments
      context: payments
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
deploy:
  kubectl: {}

# apiVersion: skaffold/v4beta11
# kind: Config
# build:
#   artifacts:
#     - image: us.gcr.io/ticketing-dev-433712/auth
#       context: auth
#       sync:
#         manual:
#           - src: src/**/*.ts
#             dest: .
#       docker:
#         dockerfile: Dockerfile
#   # local:
#   #   push: false
#   googleCloudBuild:
#     projectId: ticketing-dev-433712
# manifests:
#   rawYaml:
#     - ./infra/k8s/*
# deploy:
#   kubectl: {}